name: Update CSV File

on:
  
  schedule:
    - cron: '0 0 * * 0'
  # You can also run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install -r workflow_requirements.txt

    - name: Update resale dataset
      run: python ./src/update_csv.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "actions: update HDB database file" || echo "no changes to commit"
        git push

    - name: Update mrts
      run: python ./src/update_mrts.py

    - name: Commit and push changes
      run: |
        git add -A 
        git commit -m "actions: update MRT database file" || echo "no changes to commit"
        git push